apiVersion: cloudfront.services.k8s.aws/v1alpha1
kind: Distribution
metadata:
  name: cloudfront-distribution
spec:
  distributionConfig:
    enabled: true
    isIPV6Enabled: true
    defaultRootObject: "index.html"
    aliases:
      - {{ .Values.accessUrl }}
    priceClass: "PriceClass_200"
    origins:
      - id: {{ template "helm-access.s3OriginID" . }}
        domainName: {{ .Values.s3WebsiteEndpoint }}
        customOriginConfig:
          httpPort: 80
          httpsPort: 443
          originProtocolPolicy: "http-only"
          originSslProtocols:
            - "TLSv1"
            - "TLSv1.1"
            - "TLSv1.2"
    defaultCacheBehavior:
      allowedMethods:
        - "DELETE"
        - "GET"
        - "HEAD"
        - "OPTIONS"
        - "PATCH"
        - "POST"
        - "PUT"
      cachedMethods:
        - "GET"
        - "HEAD"
      targetOriginId: {{ template "helm-access.s3OriginID" . }}
      viewerProtocolPolicy: "allow-all"
      minTTL: 0
      defaultTTL: 3600
      maxTTL: 86400
      forwardedValues:
        queryString: false
        cookies:
          forward: "none"
    viewerCertificate:
      acmCertificateArn: {{ .Values.accessCert }}
      cloudfrontDefaultCertificate: true
      sslSupportMethod: "sni-only"
    restrictions:
      geoRestriction:
        restrictionType: "none"
    tags:
      Environment: "production"
