apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: {{ .Values.accessUrl }}
spec:
  bucketName: {{ .Values.accessUrl }}
  accessControl: "public-read"
  websiteConfiguration:
    indexDocument: "index.html"
    errorDocument: "index.html"
  corsConfiguration:
    corsRules:
      - allowedHeaders:
          - "*"
        allowedMethods:
          - "PUT"
          - "POST"
        allowedOrigins:
          - "*"
        exposeHeaders:
          - "ETag"
        maxAgeSeconds: 3000
