apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ack-infra-multi
spec:
  generators:
  - clusters: 
      selector: 
        matchLabels:         # ← pulls in every `argocd cluster add`
          app: "csoc"

  template:
    metadata:
      name: "{{.name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: gen3-commons
      sources:
        - repoURL: github.com/jayadeyemi/gen3-dev.git
          targetRevision: HEAD
          path: charts/ack-infra
          helm:
            releaseName: ack-infra
            valueFiles:
              - values/{{.valuesDirInfra}}/values.yaml
      destination:
        server: "{{.server}}"
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
