apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ack-controllers-multi
spec:
  generators:
  - list:
      elements:
      - cluster: kind-gen3-csoc
        server: "https://kubernetes.default.svc"
        valuesDir: dev
      - cluster: kind-gen3-csoc
        server: "https://kubernetes.default.svc"
        valuesDir: staging
      - cluster: kind-gen3-csoc
        server: "https://kubernetes.default.svc"
        valuesDir: prod

  template:
    metadata:
      name: "ack-controllers-{{.valuesDir}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: gen3-commons
      source:
        repoURL: https://github.com/jayadeyemi/gen3-dev.git
        targetRevision: HEAD
        path: charts/ack-controllers
        helm:
          valueFiles:
          - values/ack-controllers/{{.valuesDir}}/values.yaml
      destination:
        server: "{{.server}}"
        namespace: {{.namespace}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
