# Global mode: "eks" or "managed-amzn" or "managed-debian" or "managed-linux" or "managed-ubuntu"
mode: managed-debian
# deploymentType: "local" or "ec2" or "eks"
deploymentType: local

aws:
  region: us-east-1
  accountId: 123456789012    # your AWS account ID

cluster:
  name: my-eks-cluster       # only used in eks mode

oidc:
  bucket: iam-ack-bucket-580686     # only used in managed mode

ackNamespace: ack-system
chartRepoBase: oci://public.ecr.aws/aws-controllers-k8s

# Default values applied to all controllers unless overridden
defaults:
  chartVersion: 1.0.0
  replicaCount: 1
  serviceAccount:
    create: true
    namePrefix: ack-
    nameSuffix: -controller
    # Optional: annotations can be overridden per controller
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  image:
    # use '%name%' placeholder to be replaced by service name
    repositoryPattern: public.ecr.aws/aws-controllers-k8s/%name%-controller
    tag: v1.0.0

# Controller‑specific overrides
controllers:
  - name: s3
    chartVersion: 1.0.28
    image:
      tag: v0.1.0
  - name: vpc
    # inherits all defaults
  - name: ec2
    replicaCount: 2
    resources:
      requests:
        cpu: 200m
        memory: 256Mi