apiVersion: kro.run/v1alpha1
kind: EksclusterWithVpc
metadata:
  name: eks-cluster-with-vpc
  namespace: ack-system              # <--- change (or add) this line
spec:
  name: demo-eks-cluster-with-vpc
  tenant: "demo"
  environment: "staging"
  region: "us-east-1"
  k8sVersion: "1.33"
  accountId: ""
  managementAccountId: "12345325"
  adminRoleName: "Admin"
  fleetSecretManagerSecretNameSuffix: "argocd-secret"
  domainName: ""
  cidr:
    vpcCidr: "10.0.0.0/16"
    publicSubnet1Cidr: "10.0.1.0/24"
    publicSubnet2Cidr: "10.0.2.0/24"
    privateSubnet1Cidr: "10.0.11.0/24"
    privateSubnet2Cidr: "10.0.12.0/24"
  workloads: "false"
  addons:
    enable_metrics_server: "false"
    enable_external_secrets: "false"
    enable_external_dns: "false"
    enable_adot_collector: "false"
    enable_cw_prometheus: "false"
    enable_kyverno: "false"
    enable_kyverno_policies: "false"
    enable_kyverno_policy_reporter: "false"
    enable_cni_metrics_helper: "false"
    enable_prometheus_node_exporter: "false"
    enable_kube_state_metrics: "false"
    enable_opentelemetry_operator: "false"
    enable_cert_manager: "false"
    enable_ack_iam: "false"
    enable_ack_eks: "false"
    enable_ack_efs: "false"
    enable_aws_efs_csi_driver: "false"
    # adot parameters
    adot_collector_namespace: "adot-collector-kubeprometheus"
    adot_collector_service_account: "adot-collector-kubeprometheus"
    # external dns parameters
    external_dns_namespace: "external-dns"
    external_dns_service_account: "external-dns-sa"
    external_dns_policy: "sync"
    # external secrets parameters
    external_secrets_namespace: "external-secrets"
    external_secrets_service_account: "external-secrets-sa"
    # aws_load_balancer_controller_namespace: string | default="kube-system"
    # aws_load_balancer_controller_service_account: string | default="aws-load-balancer-controller-sa"
    amp_endpoint_url: ""
    # karpenter_namespace: string | default="karpenter"
    # karpenter_service_account: string | default="karpenter-sa"
    # karpenter_sqs_queue_name: string | default=""
