apiVersion: v2
name: my-ack-project
description: |
  Installs ACK service controllers and deploys S3 Bucket & VPC CRs
type: application
version: 0.1.0

dependencies:
  - name: s3-chart
    alias: s3
    version: "latest"
    repository: oci://public.ecr.aws/aws-controllers-k8s/s3-chart
  - name: ec2-chart
    alias: ec2
    version: "latest"
    repository: oci://public.ecr.aws/aws-controllers-k8s/ec2-chart

apiVersion: v2
name: ack-controllers
description: Install ACK controllers + demo S3 & VPC custom resources
type: application
version: 0.1.0

# Sub‑charts resolved at install‑time from ECR OCI registry
dependencies:
{{- range $svc := (split "," .Values.controllers) }}
  - name: {{ $svc }}-chart
    alias: {{ $svc }}
    version: {{ $.Values.chartVersion }}
    repository: "oci://public.ecr.aws/aws-controllers-k8s/{{ $svc }}-chart"
{{- end }}
