apiVersion: v2
name: ack-controllers
description: Umbrella chart for AWS Controllers for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: ack-chart
    version: "46.25.10"
    alias: ack
    repository: "oci://public.ecr.aws/aws-controllers-k8s"