global:
  # This can be anything you want! 
  hostname: "localhost:8081:

fence: 
  FENCE_CONFIG:
    OPENID_CONNECT:
      google:
        client_id: "109864477426-lsdtp4kvg1pg2ere50l82fmu5vmv8i3u.apps.googleusercontent.com"
        client_secret: "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"

# Use a prebuilt portal image if you're deploying to a laptop, less resources consumed by gen3
portal:
  resources:
    requests:
      cpu: "0.2"
      memory: 100Mi
  image:
    repository: quay.io/cdis/data-portal-prebuilt
    tag: dev

