{{- range $env, $cluster := .Values.argo.clusters }}
{{- if index $.Values.environments $env }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-{{ $env }}
  namespace: {{ $.Values.argo.namespace }}
spec:
  project: {{ $.Values.argo.project }}
  source:
    repoURL:        {{ $.Values.repo.url }}
    targetRevision: {{ $.Values.repo.revision }}
    path:           {{ $.Values.repo.chartsPath }}
    helm:
      valueFiles:
        - environments/{{ $env }}/secrets.yaml
  destination:
    server:    {{ $cluster.server }}
    namespace: {{ $cluster.namespace }}
  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
---
{{- end }}
{{- end }}
