{{- if .Values.vpc.enabled }}
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: VPC
metadata:
  name: {{ .Values.vpc.name | lower | quote }}
  namespace: "ack-network"  
spec:
  cidrBlocks:
    - {{ .Values.vpc.cidrBlock }}
  enableDNSHostnames: true
  enableDNSSupport: true
  tags:
    {{- range $k, $v := .Values.vpc.tags }}
    - key: {{ $k }}
      value: {{ $v | quote }}
    {{- end }}
{{- end }}