apiVersion: eksctl.io/v1alpha5
kind: Cluster
metadata:
  name: prod-cluster
  region: us-east-1
  version: "1.27"
  
# point at an existing, well-architected VPC
vpc:
  name: "prod-vpc"
  cidr: "10.0.0.0/16"
  subnets:
    public:
      public-subnet-1: "10.0.0.0/24"
      public-subnet-2: "10.0.1.0/24"
    private:
      private-subnet-1: "10.0.2.0/24"
      private-subnet-2: "10.0.3.0/24"

# control plane endpoint access
privateCluster:
  enabled: true
  
# API server logging, encryption, tags
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
secretsEncryption:
  provider: "aws"
  keyARN: "arn:aws:kms:us-east-1:123456789012:key/abcd-ef01-2345-6789"

nodeGroups:
  - name: ng-standard
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true       # no public IPs on nodes
    labels: { role: worker }

# then:
# eksctl create cluster -f cluster.yaml
