{{- if .Values.vpc.enabled }}
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: VPC
metadata:
  name: {{ .Values.vpc.name | lower | quote }}
spec:
  cidrBlocks:
    - {{ .Values.vpc.cidrBlock1 }}
  {{- if .Values.vpc.cidrBlock2 }}
    {{ .Values.vpc.cidrBlock2 }}
  {{- end }}
  {{- if .Values.vpc.cidrBlock3 }}
    {{ .Values.vpc.cidrBlock3 }}
  {{- end }}
  {{- if .Values.vpc.cidrBlock4 }}
    {{ .Values.vpc.cidrBlock4 }}
  {{- end }}
  {{- if .Values.vpc.enableDNSHostnames }}
  enableDNSHostnames: {{ .Values.vpc.enableDNSHostnames }}
  {{- end }}
  {{- if .Values.vpc.enableDNSSupport }}
  enableDNSSupport: {{ .Values.vpc.enableDNSSupport }}
  {{- end }}
  tags:
    {{- range .Values.vpc.tags }}
      {{- range $k, $v := . }}
    - key: {{ $k | quote }}
      value: {{ $v | quote }}
      {{- end }}
    {{- end }}
{{- end }}