vpc:
  enabled: true
  name: "demo-vpc-ack"
  cidrBlock1: "172.16.0.0/16"
  cidrBlock2: ""
  cidrBlock3: ""
  cidrBlock4: ""
  enableDNSHostnames: true
  enableDNSSupport: true
  tags:
    - Name: "demo-vpc-ack"
    - environment: demo
    - provisioner: terraform-helm-ack

    # additional tags
