jobs:
  promote-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Read staging toggle
      - name: Check if staging enabled
        id: check_staging
        run: |
          echo "::set-output name=enabled::$(yq e '.environments.staging' argo/app-of-apps-chart/values.yaml)"

      # Read prod toggle
      - name: Check if prod enabled
        id: check_prod
        run: |
          echo "::set-output name=enabled::$(yq e '.environments.prod' argo/app-of-apps-chart/values.yaml)"

      # … your promote staging→green commit here …

      - name: Deploy to EKS Staging
        if: steps.check_staging.outputs.enabled == 'true'
        run: |
          aws eks update-kubeconfig --name "${STAGING_CLUSTER}" --region "${AWS_REGION}"
          helm upgrade --install web-staging charts/web \
            --namespace web-staging --create-namespace \
            --values environments/prod/values-green.yaml

      - name: Deploy to EKS Production
        if: steps.check_prod.outputs.enabled == 'true'
        run: |
          aws eks update-kubeconfig --name "${PROD_CLUSTER}" --region "${AWS_REGION}"
          helm upgrade --install web-prod charts/web \
            --namespace web-prod --create-namespace \
            --values environments/prod/values-green.yaml
