name: Promote-to-Prod

on:
  push:
    branches: [main]
    paths:
      - 'charts/**'
      - 'environments/staging/**'

jobs:
  promote:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # so we can push back

      - name: Copy staging → prod (green slot)
        run: |
          cp environments/staging/values.yaml environments/prod/values-green.yaml

      - name: Commit & push prod values
        run: |
          git config user.email "ci-bot@myorg.com"
          git config user.name  "CI Bot"
          git add environments/prod/values-green.yaml
          git commit -m "Promote staging to prod (green)"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
